### ISSUE TITLE
Team Review Ticket 21

### ISSUE THREAD

**Issue by Martynguyen64** [Martynguyen64/Martins-Blog#18]
- [ ] [Martins Peer Grade](https://github.com/vivianknee/FastPages/issues/29#issue-1580229917)
- [ ] [Ethans Peer Grade](https://github.com/ahadb63/ahadsblog/issues/20)
- [ ] [Dereks Peer Grade](https://github.com/DerekSol/Tera/issues/21)
- [ ] [Jagger Peer Grade](https://github.com/JoshuaW03628/Repository-1/issues/20#issue-1578495084)
- [ ] [James Peer Grade](url)
